on: push
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            **/Dockerfile
    outputs:
      version_matrix: ${{ toJSON((steps.changed-files.outputs.all_changed_files) }}
  ci:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.version }}
      - run: echo ${{ matrix.version }}
      - run: npm test
